name: Run Integration Tests

on:
  push:
    branches: [main]
  pull_request:

env:
  EMPTY_TEST_ENVIRONMENT_ID: ${{ secrets.EMPTY_TEST_ENVIRONMENT_ID }}
  EXPORT_IMPORT_TEST_DATA_ENVIRONMENT_ID: ${{ secrets.EXPORT_IMPORT_TEST_DATA_ENVIRONMENT_ID }}
  CLEAN_TEST_DATA_ENVIRONMENT_ID: ${{ secrets.CLEAN_TEST_DATA_ENVIRONMENT_ID }}
  SYNC_SOURCE_TEST_ENVIRONMENT_ID:  ${{ secrets.SYNC_SOURCE_TEST_ENVIRONMENT_ID }}
  SYNC_TARGET_TEST_ENVIRONMENT_ID:  ${{ secrets.SYNC_TARGET_TEST_ENVIRONMENT_ID }}
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js from .nvmrc file
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run test:integration
